### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by sahildua2305** [nealrs/twittersearchreport#1]
Why not create a requirements.txt with all the dependencies to install everything at once without assuming what all a user may already have in local machine?

**Comment by nealrs** [comment]
Because I'm lazy coder 🙃. PRs welcome!

On Friday, June 17, 2016, Sahil Dua notifications@github.com wrote:

> Why not create a requirements.txt with all the dependencies to install
> everything at once without assuming what all a user may already have in
> local machine?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nealrs/twittersearchreport/issues/1, or mute the
> thread
> https://github.com/notifications/unsubscribe/ABftvCSmK2q1lci9swYyK8vWv082NlzCks5qMufXgaJpZM4I4njR
> .

## 

_Neal Shyam_ http://nealshyam.com
nealrs@gmail.com
twitter https://twitter.com/nealrs | devpost http://devpost.com/nealrs
| github https://github.com/nealrs

**Comment by sahildua2305** [comment]
Closed without fixing? @nealrs
